version: '3.7'

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: usersddb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Nukazama7
    ports:
      - "5433:5432"
    volumes:
      - my-db:/var/lib/postgresql/data
    networks:
      - backend

  backend_user:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_IP=postgres
      - DB_PORT=5432
      - DB_DBNAME=usersddb
      - DB_USER=postgres
      - DB_PASSWORD=Nukazama7
    networks:
      backend:
        ipv4_address: 172.30.1.1
    depends_on:
      - postgres

volumes:
  my-db:

networks:
  backend:
    external: true
